---
'@lightmill/log-server': patch
---

Fix SqliteDataStore not throwing the proper DataStoreError when trying to create a run for an unknown experiment.
